TOP=../..
include $(TOP)/configure/CONFIG

# Crow C++ microframework for web apps and APIs

INC += crow.h
INC += crow/app.h
INC += crow/ci_map.h
INC += crow/common.h
INC += crow/compression.h
INC += crow/exceptions.h
INC += crow/http_connection.h
INC += crow/http_parser_merged.h
INC += crow/http_request.h
INC += crow/http_response.h
INC += crow/http_server.h
INC += crow/json.h
INC += crow/logging.h
INC += crow/middleware_context.h
INC += crow/middleware.h
INC += crow/mime_types.h
INC += crow/multipart.h
INC += crow/multipart_view.h
INC += crow/mustache.h
INC += crow/parser.h
INC += crow/query_string.h
INC += crow/returnable.h
INC += crow/routing.h
INC += crow/settings.h
INC += crow/socket_acceptors.h
INC += crow/socket_adaptors.h
INC += crow/task_timer.h
INC += crow/TinySHA1.hpp
INC += crow/utility.h
INC += crow/version.h
INC += crow/websocket.h
INC += crow/middlewares/cookie_parser.h
INC += crow/middlewares/cors.h
INC += crow/middlewares/session.h
INC += crow/middlewares/utf-8.h

include $(TOP)/configure/RULES
