TOP=../..
include $(TOP)/configure/CONFIG

# Library for simplifying enum -> string bidirectional conversions
INC += magic_enum/magic_enum_containers.hpp
INC += magic_enum/magic_enum_flags.hpp
INC += magic_enum/magic_enum_format.hpp
INC += magic_enum/magic_enum_fuse.hpp
INC += magic_enum/magic_enum.hpp
INC += magic_enum/magic_enum_iostream.hpp
INC += magic_enum/magic_enum_switch.hpp
INC += magic_enum/magic_enum_utility.hpp

include $(TOP)/configure/RULES